version: '3.9'
services:
  
  crud-php:
     build: . 
     image: php:7.4-apache
     volumes:
       - ./:/var/www/html
     ports:
       - 80:80
  basedatos:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1